spring:
  application:
    name: patient-module
  datasource:
    url: jdbc:mysql://localhost:3306/mysqldb
    username: root
    password: MySql@123  
  cloud:
    config:  
      uri: http://localhost:8888

 